Snake_PPO:
  Train:
    num_envs: 32
    Config:
      time_steps: 30000
      summary_freq: 1000
  # Inference:
  #   seed: 0
  #   Config:
  #     episodes: 3
  #     export: render_only
  Agent:
    n_steps: 16
    epoch: 3
    mini_batch_size: 32
    device: cuda
