Snake_PPO:
  Train:
    num_envs: 16
    Config:
      time_steps: 500000
      summary_freq: 1000
  # Inference:
  #   seed: 0
  #   Config:
  #     episodes: 3
  #     export: render_only
  Agent:
    n_steps: 32
    epoch: 8
    mini_batch_size: 16
    device: cuda
